name: Run SAS Unit
description: Runs the specified SAS Unit version on the given script
inputs:
  sasUnitVersion:
    description: Version of SAS Unit to use
    required: true
  sasUnitPath:
    description: Path to the chosen SAS Unit version
    required: true
  script:
    description: The script to run
    required: true
  shell:
    description: Shell to use
    required: true
  language:
    required: true

runs:
  using: "composite"

  steps:
    - name: Run SAS Test
      env:
        SASUNIT_HOST_OS: windows
        SASUNIT_HOST_ENCODING: PCOEM850
        SASUNIT_SAS_VERSION: 9.4
        SASUNIT_SAS_EXE: C:/Program Files/SASHome2/SASFoundation/9.4/sas.exe
        SASUNIT_SAS_CFG: C:/Program Files/SASHome2/SASFoundation/9.4/nls/${{ inputs.language }}/sasv9.cfg

        # EnvVars for SAS Unit Configuration 
        # TODO replace all occurences with ${{ github.workspace }}
        SASUNIT_ROOT: C:/actions-runner/_work/SASUnit/SASUnit
        SASUNIT_PROJECT_ROOT: C:/actions-runner/_work/SASUnit/SASUnit
        SASUNIT_TEST_DB_FOLDER: C:/actions-runner/_work/SASUnit/SASUnit/${{ inputs.language }}/testdb
        SASUNIT_LOG_FOLDER: C:/actions-runner/_work/SASUnit/SASUnit/${{ inputs.language }}/logs
        SASUNIT_SCN_LOG_FOLDER: C:/actions-runner/_work/SASUnit/SASUnit/${{ inputs.language }}/scn_logs
        SASUNIT_RUNALL: C:/actions-runner/_work/SASUnit/SASUnit/saspgm/test/run_all.sas
        SASUNIT_REPORT_FOLDER: C:/actions-runner/_work/SASUnit/SASUnit/${{ inputs.language }}/doc
        SASUNIT_RESOURCE_FOLDER: C:/actions-runner/_work/SASUnit/SASUnit/resources
        SASUNIT_LANGUAGE: ${{ inputs.language }}
        SASUNIT_OVERWRITE: 0
        SASUNIT_COVERAGEASSESSMENT: 0
        SASUNIT_PGMDOC: 0
        SASUNIT_PGMDOC_SASUNIT: 0
        SASUNIT_CROSSREFERENCE: 0
        SASUNIT_CROSSREFERENCE_SASUNIT: 0
        SASUNIT_LOGLEVEL: INFO
        SASUNIT_SCN_LOGLEVEL: INFO
      shell: ${{ inputs.shell }}
      run: |
        mkdir doc/spec
        mkdir saspgm/test/reportsasunit_inexisting_scenario_has_to_fail
        Invoke-Expression 'C:/Program` Files/SASHome2/SASFoundation/9.4/sas.exe -CONFIG "bin/sasunit.${{ env.SASUNIT_SAS_VERSION }}.${{ env.SASUNIT_HOST_OS }}.${{ env.SASUNIT_LANGUAGE }}.cfg" -no$syntaxcheck -noovp -nosplash -LOGCONFIGLOC "bin/sasunit.logconfig.${{ inputs.language }}.xml"'
        echo $LastExitCode $?
