name: Run SAS Unit
description: Runs the specified SAS Unit version on the given script
inputs:
  sasUnitVersion:
    description: Version of SAS Unit to use
    required: true
  sasUnitPath:
    description: Path to the chosen SAS Unit version
    required: true
  script:
    description: The script to run
    required: true
  shell:
    description: Shell to use
    required: true

runs:
  using: "composite"
  steps:
    - name: Run SAS Test
      run: ${{ inputs.sasUnitPath }} "${{ inputs.script }}"
      shell: ${{ inputs.shell }}
