name: Run SAS Setup
description: Creates neccessary files and runs setup scripts.
inputs:
  language:
    description: Either de or en
    required: true
  shell:
    description: Shell to use
    required: true

runs:
  using: "composite"

  steps:
    # TODO Find a way to use the same script for both platforms
    - name: Set General Env (Linux)
      shell: ${{ inputs.shell }}
      if: runner.os == 'Linux'
      run: |
        echo SASUNIT_HOST_OS=linux >> $GITHUB_ENV
        echo SASUNIT_HOST_ENCODING=UTF8 >> $GITHUB_ENV
        echo SASUNIT_SAS_VERSION=9.4 >> $GITHUB_ENV
        echo SASUNIT_LANGUAGE=${{ inputs.language }} >> $GITHUB_ENV
        echo SASUNIT_ROOT=$WORKSPACE >> $Env:GITHUB_ENV
        echo SASUNIT_PROJECTROOT=$WORKSPACE >> $Env:GITHUB_ENV
        echo SASUNIT_LOG_LEVEL=INFO >> $GITHUB_ENV
        echo SASUNIT_SCN_LOG_LEVEL=INFO >> $GITHUB_ENV

    - name: Set General Env (Windows)
      shell: ${{ inputs.shell }}
      if: runner.os == 'Windows'
      run: |
        echo SASUNIT_HOST_OS=linux >> $Env:GITHUB_ENV
        echo SASUNIT_HOST_ENCODING=UTF8 >> $Env:GITHUB_ENV
        echo SASUNIT_SAS_VERSION=9.4 >> $Env:GITHUB_ENV
        echo SASUNIT_LANGUAGE=${{ inputs.language }} >> $Env:GITHUB_ENV
        echo SASUNIT_ROOT=$Env:WORKSPACE >> $GITHUB_ENV
        echo SASUNIT_PROJECTROOT=$Env:WORKSPACE >> $GITHUB_ENV
        echo SASUNIT_LOG_LEVEL=INFO >> $Env:GITHUB_ENV
        echo SASUNIT_SCN_LOG_LEVEL=INFO >> $Env:GITHUB_ENV

    - name: Set paths (Linux)
      if: runner.os == 'Linux'
      shell: ${{ inputs.shell }}
      run: |
       echo SASUNIT_SAS_EXE=/opt/sas/sas94M7/SASFoundation/$SASUNIT_SAS_VERSION/bin/sas_$SASUNIT_LANGUAGE >> $GITHUB_ENV
       echo SASUNIT_SAS_CFG=/opt/sas/sas94M7/SASFoundation/$SASUNIT_SAS_VERSION/nls/$SASUNIT_LANGUAGE/sasv9.cfg >> $GITHUB_ENV
       echo SASUNIT_TESTDB_PATH=$SASUNIT_PROJECTROOT/$SASUNIT_LANGUAGE/testdb >> $GITHUB_ENV
       echo SASUNIT_LOG_PATH=$SASUNIT_PROJECTROOT/$SASUNIT_LANGUAGE/logs >> $GITHUB_ENV
       echo SASUNIT_SCN_LOG_PATH=$SASUNIT_PROJECTROOT/$SASUNIT_LANGUAGE/scn_logs >> $GITHUB_ENV
       echo SASUNIT_REPORT_PATH=$SASUNIT_PROJECTROOT/$SASUNIT_LANGUAGE/doc >> $GITHUB_ENV
       echo SASUNIT_RESOURCE_PATH=$SASUNIT_ROOT/resources >> $GITHUB_ENV
       echo SASUNIT_RUNALL=$SASUNIT_PROJECTROOT/saspgm/test/run_all.sas >> $GITHUB_ENV


    - name: Set paths (Windows)
      if: runner.os == 'Windows'
      shell: ${{ inputs.shell }}
      run: |
       echo SASUNIT_SAS_EXE=/opt/sas/sas94M7/SASFoundation/$SASUNIT_SAS_VERSION/bin/sas_$SASUNIT_LANGUAGE >> $Env:GITHUB_ENV
       echo SASUNIT_SAS_CFG=/opt/sas/sas94M7/SASFoundation/$SASUNIT_SAS_VERSION/nls/$SASUNIT_LANGUAGE/sasv9.cfg >> $Env:GITHUB_ENV
       echo SASUNIT_TESTDB_PATH=$SASUNIT_PROJECTROOT/$SASUNIT_LANGUAGE/testdb >> $Env:GITHUB_ENV
       echo SASUNIT_LOG_PATH=$SASUNIT_PROJECTROOT/$SASUNIT_LANGUAGE/logs >> $Env:GITHUB_ENV
       echo SASUNIT_SCN_LOG_PATH=$SASUNIT_PROJECTROOT/$SASUNIT_LANGUAGE/scn_logs >> $Env:GITHUB_ENV
       echo SASUNIT_REPORT_PATH=$SASUNIT_PROJECTROOT/$SASUNIT_LANGUAGE/doc >> $Env:GITHUB_ENV
       echo SASUNIT_RESOURCE_PATH=$SASUNIT_ROOT/resources >> $Env:GITHUB_ENV
       echo SASUNIT_RUNALL=$SASUNIT_PROJECTROOT/saspgm/test/run_all.sas >> $Env:GITHUB_ENV
    
    - name: Creating script files for starting SASUnit (Linux)
      if: runner.os == 'Linux'
      shell: ${{ inputs.shell }}
      env:
        ENV_CONTEXT: ${{ toJson(env) }}
      run: |
        echo "$ENV_CONTEXT"
        $SASUNIT_SAS_EXE -nosyntaxcheck -noovp -log "$SASUNIT_PROJECTROOT/bin/sasunit.setup.$SASUNIT_SAS_VERSION.$SASUNIT_LANGUAGE.log" -sysin "$SASUNIT_ROOT/saspgm/sasunit/runsasunitsetup.sas"

    - name: Creating script files for starting SASUnit (Windows)
      if: runner.os == 'Windows'
      shell: ${{ inputs.shell }}
      env:
        ENV_CONTEXT: ${{ toJson(env) }}
      run: |
        echo "$ENV_CONTEXT"
        Invoke-Expression ${{ env.SASUNIT_SAS_EXE }} -nosyntaxcheck -noovp -log "${{env.SASUNIT_PROJECTROOT}}/bin/sasunit.setup.${{env.SASUNIT_SAS_VERSION}}.${{env.SASUNIT_LANGUAGE}}.log" -sysin "${{env.SASUNIT_ROOT}}/saspgm/sasunit/runsasunitsetup.sas"
