
name: 'Remove Windows Line Endings'
inputs:
  dir:
    required: true
    default: "."
runs:
  using: "composite"
  steps:
    - name: Remove Line Endings
      shell: bash
      run: |
        sed -i -e "s/\r//g" ${{ inputs.dir }}/example/saspgm/*.sas
        sed -i -e 's/\r//g' ${{ inputs.dir }}/saspgm/sasunit/*.sas
        sed -i -e 's/\r//g' ${{ inputs.dir }}/saspgm/sasunit/*.txt
        sed -i -e 's/\r//g' ${{ inputs.dir }}/saspgm/sasunit/linux/*.sas
        sed -i -e 's/\r//g' ${{ inputs.dir }}/saspgm/sasunit/linux/*.sh
        sed -i -e 's/\r//g' ${{ inputs.dir }}/saspgm/sasunit/unix_aix/*.sas
        sed -i -e 's/\r//g' ${{ inputs.dir }}/saspgm/sasunit/unix_aix/*.sh
        sed -i -e 's/\r//g' ${{ inputs.dir }}/dat/*.txt
        sed -i -e 's/\r//g' ${{ inputs.dir }}/dat/*.xml
