runs:
  using: "composite"
  steps:
    - name: Remove Line Endings
      shell: bash
      run: |
        sed -i -e "s/\r//g" $GITHUB_ACTION_PATH/example/saspgm/*.sas
        sed -i -e 's/\r//g' $GITHUB_ACTION_PATH/saspgm/sasunit/*.sas
        sed -i -e 's/\r//g' $GITHUB_ACTION_PATH/saspgm/sasunit/*.txt
        sed -i -e 's/\r//g' $GITHUB_ACTION_PATH/saspgm/sasunit/linux/*.sas
        sed -i -e 's/\r//g' $GITHUB_ACTION_PATH/saspgm/sasunit/linux/*.sh
        sed -i -e 's/\r//g' $GITHUB_ACTION_PATH/saspgm/sasunit/unix_aix/*.sas
        sed -i -e 's/\r//g' $GITHUB_ACTION_PATH/saspgm/sasunit/unix_aix/*.sh
        sed -i -e 's/\r//g' $GITHUB_ACTION_PATH/dat/*.txt
        sed -i -e 's/\r//g' $GITHUB_ACTION_PATH/dat/*.xml