
name: 'Remove Windows Line Endings'
inputs:
  dir:
    required: true
    default: "."
runs:
  using: "composite"
  steps:
    - name: Remove Line Endings
      shell: bash
      working-directory: ${{ inputs.dir }}
      run: |
        sed -i -e "s/\r//g" ./example/saspgm/*.sas
        sed -i -e 's/\r//g' ./saspgm/sasunit/*.sas
        sed -i -e 's/\r//g' ./saspgm/sasunit/*.txt
        sed -i -e 's/\r//g' ./saspgm/sasunit/linux/*.sas
        sed -i -e 's/\r//g' ./saspgm/sasunit/linux/*.sh
        sed -i -e 's/\r//g' ./saspgm/sasunit/unix_aix/*.sas
        sed -i -e 's/\r//g' ./saspgm/sasunit/unix_aix/*.sh
        sed -i -e 's/\r//g' ./dat/*.txt
        sed -i -e 's/\r//g' ./dat/*.xml
