%macro _createBatchFiles(i_sasunitRootFolder=
                        ,i_targetFolder=
                        ,i_projectBinFolder=
                        ,i_sasunitLanguage=
                        ,i_operatingSystem=
                        ,i_sasVersion=
                        ,i_sasexe=
                        );

   %_createBatchFile(i_sasunitCommandFile=&i_targetFolder./sasunit.&i_sasVersion..&i_operatingSystem..&i_sasunitLanguage..overwrite
                    ,i_sasunitRootFolder=&i_sasunitRootFolder.
                    ,i_projectBinFolder=&i_projectBinFolder.
                    ,i_sasunitOverwrite=1
                    ,i_sasunitLanguage=&i_sasunitLanguage.
                    ,i_operatingSystem=&i_operatingSystem.
                    ,i_sasunitTestCoverage=1
                    ,i_sasunitPgmDoc=1
                    ,i_sasunitPgmDocSASUnit=1
                    ,i_sasunitCrossRef=1
                    ,i_sasunitCrossRefSASUnit=1
                    ,i_sasunitVerbose=1
                    ,i_sasVersion=&i_sasVersion.
                    ,i_sasexe=&i_sasexe.
                    ,i_sasunitJenkinsPlugin=0
                    );
   %_createBatchFile(i_sasunitCommandFile=&i_targetFolder./sasunit.&i_sasVersion..&i_operatingSystem..&i_sasunitLanguage.
                    ,i_sasunitRootFolder=&i_sasunitRootFolder.
                    ,i_projectBinFolder=&i_projectBinFolder.
                    ,i_sasunitOverwrite=0
                    ,i_sasunitLanguage=&i_sasunitLanguage.
                    ,i_operatingSystem=&i_operatingSystem.
                    ,i_sasunitTestCoverage=1
                    ,i_sasunitPgmDoc=1
                    ,i_sasunitPgmDocSASUnit=0
                    ,i_sasunitCrossRef=1
                    ,i_sasunitCrossRefSASUnit=0
                    ,i_sasunitVerbose=1
                    ,i_sasVersion=&i_sasVersion.
                    ,i_sasexe=&i_sasexe.
                    ,i_sasunitJenkinsPlugin=0
                    );
   %_createBatchFile(i_sasunitCommandFile=&i_targetFolder./sasunit.&i_sasVersion..&i_operatingSystem..&i_sasunitLanguage..overwrite.ci
                    ,i_sasunitRootFolder=&i_sasunitRootFolder.
                    ,i_projectBinFolder=&i_projectBinFolder.
                    ,i_sasunitOverwrite=1
                    ,i_sasunitLanguage=&i_sasunitLanguage.
                    ,i_operatingSystem=&i_operatingSystem.
                    ,i_sasunitTestCoverage=1
                    ,i_sasunitPgmDoc=1
                    ,i_sasunitPgmDocSASUnit=1
                    ,i_sasunitCrossRef=1
                    ,i_sasunitCrossRefSASUnit=1
                    ,i_sasunitVerbose=1
                    ,i_sasVersion=&i_sasVersion.
                    ,i_sasexe=&i_sasexe.
                    ,i_sasunitJenkinsPlugin=1
                    );
   %_createBatchFile(i_sasunitCommandFile=&i_targetFolder./sasunit.&i_sasVersion..&i_operatingSystem..&i_sasunitLanguage..ci
                    ,i_sasunitRootFolder=&i_sasunitRootFolder.
                    ,i_projectBinFolder=&i_projectBinFolder.
                    ,i_sasunitOverwrite=0
                    ,i_sasunitLanguage=&i_sasunitLanguage.
                    ,i_operatingSystem=&i_operatingSystem.
                    ,i_sasunitTestCoverage=1
                    ,i_sasunitPgmDoc=1
                    ,i_sasunitPgmDocSASUnit=1
                    ,i_sasunitCrossRef=1
                    ,i_sasunitCrossRefSASUnit=1
                    ,i_sasunitVerbose=1
                    ,i_sasVersion=&i_sasVersion.
                    ,i_sasexe=&i_sasexe.
                    ,i_sasunitJenkinsPlugin=1
                    );
%mend _createBatchFiles;
