name: Feature Request
description: File a faeture request
title: "[Enhancement]: "
labels: ["enhancement"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: What is the new faeture you want to see in SASUnit?
      placeholder: Tell us what you need!
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Release
      description: Which release of SASUnit are you running?
      options:
        - 2.1 (Default)
        - 2.0.2 (July 2019)
        - 2.0 (June 2018)
        - 1.7 (July 2017)
        - 1.6.1 (June 2017)
        - 1.6 (February 2016)
        - 1.5 (February 2015)
        - 1.3 (March 2014)
        - 1.2.1 (February 2013)
        - 1.2 (February 2014)
        - 1.1 (April 2010)        
    validations:
      required: false
  - type: dropdown
    id: component
    attributes:
      label: SASUnit Component
      description: Which component of SASUnit is affected?
      options:
        - Framework (Feature request having an impact on many or all components)
        - Assertions (Feature request for assertions)
        - Reporting (Feature request for the reporting output of SASUnit)
        - Tests (Feature request for SASUnit tests)
        - Unknown (General feature request)
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true