
name: Setting Execution Rights of Shell Scripts

inputs:
  dir:
    default: "."

runs:
  using: "composite"
  steps:
    - name: Set execution rights
      shell: bash
      working-directory: ${{ inputs.dir }}
      run: |
        chmod a+x ./bin/sasunit.setup.EE_CI_CentOS*sh
        chmod a+x ./example/bin/sasunit.setup.EE_CI_CentOS*sh
        chmod a+x ./saspgm/sasunit/linux/assert*.sh
        chmod a+x ./saspgm/sasunit/unix_aix/assert*.sh
        chmod a+x ./.github/scripts/*.sh
        
