runs:
  using: "composite"
  steps:
    - name: Set execution rights
      shell: bash
      run: |
        chmod a+x bin/sasunit.setup.EE_CI_CentOS*sh
        chmod a+x example/bin/sasunit.setup.EE_CI_CentOS*sh
        chmod a+x saspgm/sasunit/linux/assert*.sh
        chmod a+x saspgm/sasunit/unix_aix/assert*.sh
