name: Cleanup Old Runs
  
on:
  push:
  schedule: 
    - cron: "0 12 1 * *" # the first of each month at 12:00
  workflow_dispatch:

env:
  RUNS_TO_KEEP: 10

jobs:
  cleanup:
    runs-on: SASUnit_CentOS
    steps:
      - name: "Delete Old Runs"
        run: |
          ./github/scripts/mount_p_drive.sh
          
          files=$(ls /media/github)
          filecount=$(echo "$files" | wc -l)
          filescount2del=$(expr $file_count - ${{ RUNS_TO_KEEP }})
          files2del=$(echo "$files" | sort | head -n $filescount2del)

          echo "found $filecount will delete $files2del"
          echo "deleting the following runs"
          echo "$files2del"

          echo "THIS IS A DRY RUN, NOTHING WAS DELETED"
          # echo "$files2del" | xargs -I {} bash -c "echo rm {}; rm -r {}"
