
on:
  push:
    branches:
      - '**'

jobs:
  test:
    name: Run Self Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [en, de]
    steps:
      - uses: actions/checkout@v3
      - name: Remove Line Endings
        run: |
          cd example/saspgm/
          sed -i -e "s/\r//g" ./*.sas
          cd saspgm/sasunit
          sed -i -e 's/\r//g' ./*.sas
          sed -i -e 's/\r//g' ./*.txt
          cd saspgm/sasunit/linux
          sed -i -e 's/\r//g' ./*.sas
          sed -i -e 's/\r//g' ./*.sh
          cd saspgm/sasunit/unix_aix
          sed -i -e 's/\r//g' ./*.sas
          sed -i -e 's/\r//g' ./*.sh
          cd dat
          sed -i -e 's/\r//g' ./*.txt
          sed -i -e 's/\r//g' ./*.xml 
      - name: Set execution rights
        run: |
          cd bin
          chmod a+x sasunit.setup.EE_CI_CentOS*sh
          cd ..
          cd example/bin
          chmod a+x sasunit.setup.EE_CI_CentOS*sh
          cd ../..
          cd saspgm/sasunit/linux
          chmod a+x assert*.sh
          cd saspgm/sasunit/unix_aix
          chmod a+x assert*.sh
      - run: cd bin && ./sasunit.setup.EE_CI_CentOS.${{ matrix.language }}.sh
      # - SASUnit Plugin: Selftest, bin/sasunit.9.4.de.fast.sh
      # - SASUnit Plugin: Selftest, bin/sasunit.9.4.linux.de.overwrite.full.sh
      - run: cd example/bin && ./sasunit.setup.EE_CI_CentOS.${{ matrix.language }}.sh
      # - SASUnit Plugin: Selftest, example/bin/sasunit.9.4.linux.de.overwrite.full.sh
      # - archive: **/*run_all.log,**/*junit.xml
      # - html report: de/doc/index.html
      # - html report: example/de/doc/index.html
      # - junit results **/*junit.xml