
on:
  push:
    branches:
      - '**'

env:
  sasUnitVersion: "Self Test"
  sasUnitPath: "C:\\jenkins1\\workspace\\00773_KF_SAS_SASUNIT\\SASUnit"

jobs:
  test:
    name: Run Self Tests
    strategy:
      matrix:
        language: [en, de]
        platform: [CentOS]
        include:
          #- platform: WIN10
          #  extension: cmd
          #  runner: Windows
          - platform: CentOS
            extension: sh
            shell: bash
            runner: Linux
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v3
      
      - if: ${{ matrix.platform == 'CentOS' }}
        uses: ./.github/actions/trim_line_endings
      - if: ${{ matrix.platform == 'CentOS' }}
        uses: ./.github/actions/set_execution_rights
      - run: bin/sasunit.setup.EE_CI_${{ matrix.platform }}.${{ matrix.extension }} ${{ matrix.language }}
      - run: example/bin/sasunit.setup.EE_CI_${{ matrix.platform }}.${{ matrix.extension }} ${{ matrix.language }}

      - uses: ./.github/actions/sas_unit
        with:
          sasUnitVersion: ${{ env.sasUnitVersion }}
          script: bin\\sasunit.9.4.windows.${{ matrix.language }}.fast.cmd
      - uses: ./.github/actions/sas_unit
        with:
          sasUnitVersion: ${{ env.sasUnitVersion }}
          script: bin\\sasunit.9.4.windows.${{ matrix.language }}.overwrite.full.cmd
      - uses: ./.github/actions/sas_unit
        with:
          sasUnitVersion: ${{ env.sasUnitVersion }}
          script: example\\bin\\sasunit.9.4.windows.${{ matrix.language }}.overwrite.full.cmd

      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: Logs and Test Results
          path: |
            "**/*run_all.log"
            "**/*junit.xml"
            ${{ matrix.language }}/doc/index.html
            example/${{ matrix.language }}/doc/index.html
          if-no-files-found: warn
      - uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test Report
          path: "**/*junit.xml"
          reporter: java-junit
