
on:
  push:
    branches:
      - '**'

jobs:
  test:
    name: Run Self Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [en, de]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/trim_line_endings
      - uses: ./.github/actions/set_execution_rights
      - run: cd bin && ./sasunit.setup.EE_CI_CentOS.${{ matrix.language }}.sh
      # - SASUnit Plugin: Selftest, bin/sasunit.9.4.de.fast.sh
      # - SASUnit Plugin: Selftest, bin/sasunit.9.4.linux.de.overwrite.full.sh
      - run: cd example/bin && ./sasunit.setup.EE_CI_CentOS.${{ matrix.language }}.sh
      # - SASUnit Plugin: Selftest, example/bin/sasunit.9.4.linux.de.overwrite.full.sh
      # - archive: **/*run_all.log,**/*junit.xml
      # - html report: de/doc/index.html
      # - html report: example/de/doc/index.html
      # - junit results **/*junit.xml