
on:
  push:
    tags:
      - 'v*'
    branches:
      - '**'

env:
  WORKSPACE: ${{ github.workspace }}

permissions:
  contents: write
  pull-requests: read

jobs:

  release:
    name: Release
    strategy:
      matrix:
        platform: [WIN10, CentOS]
        include:
          - platform: CentOS
            runner: Linux
            osName: linux
            extension: sh
          - platform: WIN10
            runner: Windows
            osName: windows
            extension: cmd

    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v3

      - if: ${{ matrix.platform == 'CentOS' }}
        uses: ./.github/actions/trim_line_endings
      - if: ${{ matrix.platform == 'CentOS' }}
        uses: ./.github/actions/set_execution_rights
      
      - name: Run examples
        run: |
          ./example/bin/sasunit.setup.EE_CI_${{ matrix.platform }}.${{ matrix.extension }} de
          ./example/bin/sasunit.setup.EE_CI_${{ matrix.platform }}.${{ matrix.extension }} en
          ./example/bin/sasunit.9.4.${{ matrix.osName }}.de.overwrite.full.${{ matrix.extension }}
          ./example/bin/sasunit.9.4.${{ matrix.osName }}.en.overwrite.full.${{ matrix.extension }}

      - name: Prepare Files
        run: |
          rm ./example/de/testdb/*.sas7bdat
          rm ./example/en/testdb/*.sas7bdat
          rm -f ./resources/style/*.sas7bitm
          rm ./example/bin/sasunit.setup.EE_*
          rm ./example/bin/sasunit.9.4.linux.*
          rm ./example/bin/*.xml
          rm ./example/bin/*.log
          rm ./example/bin/*.cmd
          rm -f *.sv*
          

      - name: Build ZIP File
        uses: TheDoctor0/zip-release@0.7.1
        with:
          filename: sasunit.${{ github.ref_name }}.${{ matrix.osName }}.zip 
          files: example/* saspgm/sasunit/* resources/* saspgm/template/* *.txt 


      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.12.0
        with:
          name: Release ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
          draft: true
          prerelease: true
          allowUpdates: true
          artifacts: |
            LICENSE.md
            sasunit.*.zip

            # - uses: actions/upload-artifact@v3
            #   with:
            #     name: logs
            #     path: |
            #       **/*run_all.log
            # - uses: actions/upload-artifact@v3
            #   with:
            #     name: example_en
            #     path: example/en/doc/
            # - uses: actions/upload-artifact@v3
            #   with:
            #     name: example_de
            #     path: example/de/doc/

