
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  WORKSPACE: ${{ github.workspace }}

permissions:
  contents: write
  pull-requests: read

jobs:
  release:
    name: Build Release Zip
    continue-on-error: true
    strategy:
      matrix:
        platform: [CentOS]
        include:
          - platform: CentOS
            runner: Linux
            osName: linux
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v3

      - if: ${{ matrix.platform == 'CentOS' }}
        uses: ./.github/actions/trim_line_endings
      - if: ${{ matrix.platform == 'CentOS' }}
        uses: ./.github/actions/set_execution_rights
      
      - name: Run examples
        run: |
          ./example/bin/sasunit.setup.EE_CI_CentOS.sh de
          ./example/bin/sasunit.setup.EE_CI_CentOS.sh en
          ./example/bin/sasunit.9.4.linux.de.overwrite.full.sh
          ./example/bin/sasunit.9.4.linux.en.overwrite.full.sh

      - name: Build ZIP File
        run: |
          rm ./example/de/testdb/*.sas7bdat
          rm ./example/en/testdb/*.sas7bdat
          rm -f ./resources/style/*.sas7bitm
          rm ./example/bin/sasunit.setup.EE_*
          rm ./example/bin/sasunit.9.4.linux.*
          rm ./example/bin/*.xml
          rm ./example/bin/*.log
          rm ./example/bin/*.cmd

          zip -r sasunit.${{ GITHUB_REF_NAME }}.linux.zip example/* saspgm/sasunit/* resources/* saspgm/template/* *.txt -x \*.sv*
          zip -T sasunit.${{ GITHUB_REF_NAME }}.${{ matrix.osName }}.zip
          
      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest
          files: |
            LICENSE.md
            sasunit.*.zip

      - uses: actions/upload-artifact@v3
        with:
          name: logs
          path: |
            **/*run_all.log
      - uses: actions/upload-artifact@v3
        with:
          name: example_en
          path: example/en/doc/
      - uses: actions/upload-artifact@v3
        with:
          name: example_de
          path: example/de/doc/

