name: Sync with Public Repo

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all commits

      - run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SASUNIT_PUBLIC_REPO_PRIVATE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # use id_ra to push to public repo
          export GIT_SSH_COMMAND="ssh -i ~/.ssh/id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

          git remote add public git@github.com:HMS-Analytical-Software/SASUnit.git

          git push public main
          git push public develop
          git push public tag v*

          
