name: Sync with Public Repo

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SASUNIT_DEV_REPO_PRIVATE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          export GIT_SSH_COMMAND="ssh -i ~/.ssh/id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

          git clone git@github.com:HMS-Analytical-Software/SASUnitDev.git .
          git fetch --all --tags
          git checkout main


      - name: Push Branches and Tags
        run: |
          git remote add public git@github.com:HMS-Analytical-Software/SASUnit.git
          echo "${{ secrets.SASUNIT_PUBLIC_REPO_PRIVATE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          git push public main
          git push public tag v*

          
