name: Run Tests

on:
  push:
    branches:
      - '**'

env:
  WORKSPACE: ${{ github.workspace }}
  RUN_NUMBER: ${{ github.run_number }}

permissions: 
  contents: read
  pages: write
  id-token: write
  checks: write

jobs:
  tests:
    name: Run Self Tests
    strategy:
      fail-fast: false
      matrix:
        language: [en,de]
        platform: [WIN10, CentOS]
        include:
          - platform: WIN10
            extension: cmd
            runner: SASUnit_WIN10
            osName: windows
            copyToShare: .github/scripts/copy_to_p_drive.ps1
          - platform: CentOS
            extension: sh
            runner: SASUnit_CentOS
            osName: linux
            copyToShare: .github/scripts/copy_to_p_drive.sh

    env:
      LANGUAGE: ${{ matrix.language }}
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v3
      
      - if: ${{ matrix.platform == 'CentOS' }}
        uses: ./.github/actions/trim_line_endings
      - if: ${{ matrix.platform == 'CentOS' }}
        uses: ./.github/actions/set_execution_rights
 
      - name: Self Test
        run: |
          ./bin/sasunit.setup.EE_CI_${{ matrix.platform }}.${{ matrix.extension }} ${{ matrix.language }}
          ./bin/sasunit.9.4.${{ matrix.osName }}.${{ matrix.language }}.fast.${{ matrix.extension }}
          ./bin/sasunit.9.4.${{ matrix.osName }}.${{ matrix.language }}.overwrite.full.${{ matrix.extension }} 
          
      - name: Example Test
        run: |
          ./example/bin/sasunit.setup.EE_CI_${{ matrix.platform }}.${{ matrix.extension }} ${{ matrix.language }}
          ./example/bin/sasunit.9.4.${{ matrix.osName }}.${{ matrix.language }}.overwrite.full.${{ matrix.extension }}

      - name: Copy output to share
        run: |
          ./${{ matrix.copyToShare }} ${{ matrix.language }}/doc          ${{ matrix.osName }}_${{ matrix.language }}
          ./${{ matrix.copyToShare }} ${{ matrix.language }}/logs         ${{ matrix.osName }}_${{ matrix.language }}
          ./${{ matrix.copyToShare }} example/${{ matrix.language }}/doc  ${{ matrix.osName }}_${{ matrix.language }}/example
          ./${{ matrix.copyToShare }} example/${{ matrix.language }}/logs ${{ matrix.osName }}_${{ matrix.language }}/example


      - name: Junit Report
        uses: dorny/test-reporter@v1.7.0
        with:
          name: Test Report (${{ matrix.osName }}, ${{ matrix.language }})
          path: "**/junit.xml"
          reporter: java-junit
          # work-around: if this is > 0, the action checks for tracked files
          # but git is not installed on our nodes
          max-annotations: '0'
          fail-on-error: false

  with_spaces:
    name: Test Path with Spaces
    runs-on: SASUnit_CentOS
    env:
      WORKSPACE: "${{ github.workspace }}/dir with spaces"
      LANGUAGE: "en"
    steps:
      - uses: actions/checkout@v3
        with:
          path: ${{ env.WORKSPACE }}
 
      - uses: "./dir with spaces/.github/actions/trim_line_endings"
        with:
          dir: ${{ env.WORKSPACE }}
      - uses: "./dir with spaces/.github/actions/set_execution_rights"
        with:
          dir: ${{ env.WORKSPACE }} 
 
      - name: Self Test
        working-directory: ${{ env.WORKSPACE }}
        run: |
          ./bin/sasunit.setup.EE_CI_CentOS.sh en
          ./bin/sasunit.9.4.linux.en.fast.sh
          ./bin/sasunit.9.4.linux.en.overwrite.fast.sh
          
      - name: Example Test
        working-directory: ${{ env.WORKSPACE }}
        run: |
          ./example/bin/sasunit.setup.EE_CI_CentOS.sh en
          ./example/bin/sasunit.9.4.linux.en.overwrite.fast.sh
 
      - name: Copy output to share
        working-directory: ${{ env.WORKSPACE }}
        run: |
          ./.github/scripts/copy_to_p_drive.sh en/doc          with_spaces
          ./.github/scripts/copy_to_p_drive.sh en/logs         with_spaces
          ./.github/scripts/copy_to_p_drive.sh example/en/doc  with_spaces/example
          ./.github/scripts/copy_to_p_drive.sh example/en/logs with_spaces/example

      - name: Junit Report
        uses: dorny/test-reporter@v1.7.0
        with:
          name: Test Report (Path with Spaces)
          path: "**/junit.xml"
          reporter: java-junit
          # work-around: if this is > 0, the action checks for tracked files
          # but git is not installed on our nodes
          max-annotations: '0'
          fail-on-error: false
 
  etc-opt-var:
    name: Test Distribution on Linux System (in /etc /opt /var)
    runs-on: SASUnit_CentOS
    env:
      WORKSPACE: ${{ github.workspace }}
      LANGUAGE: "de"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/trim_line_endings
      - uses: ./.github/actions/set_execution_rights
 
      - run: |
          # Remove data from previous run
          rm -rf /etc/opt/SASUnit/*
          rm -rf /opt/SASUnit/*
          rm -rf /var/opt/SASUnit/*
          
          # Create necessary folders
          mkdir /opt/SASUnit/example
          cp -r example/* /opt/SASUnit/example/
          mkdir /opt/SASUnit/saspgm
          cp -r saspgm/* /opt/SASUnit/saspgm/
          mkdir /etc/opt/SASUnit/resources/
          cp -r resources/* /etc/opt/SASUnit/resources/

          # Create start scripts in /opt/...
          ./example/bin/sasunit.setup.EE_CI_CentOS_etcoptvar.sh de

          # Start SASUnit
          /opt/SASUnit/example/bin/sasunit.9.4.linux.de.overwrite.full.sh
 
          mkdir $WORKSPACE/example/de/
          mkdir $WORKSPACE/example/de/doc
          mkdir $WORKSPACE/example/de/logs
          cp /var/opt/SASUnit/example/de/logs/*run_all.log $WORKSPACE/example/de/logs/
          cp -r /var/opt/SASUnit/example/de/doc/* $WORKSPACE/example/de/doc


      - name: Copy output to share
        run: |
          ./.github/scripts/copy_to_p_drive.sh example/de/doc   etc_opt_var/example/
          ./.github/scripts/copy_to_p_drive.sh example/de/logs  etc_opt_var/example/

 
      - name: Junit Report
        uses: dorny/test-reporter@v1.7.0
        with:
          name: Test Report (etc-opt-var)
          path: "**/junit.xml"
          reporter: java-junit
          # work-around: if this is > 0, the action checks for tracked files
          # but git is not installed on our nodes
          max-annotations: '0'
          fail-on-error: false


  github_pages:
    name: Upload Results to Github Pages
    runs-on: SASUnit_CentOS
    needs: tests
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup Github Pages
        uses: actions/configure-pages@v3

      - name: Build Page
        run: ./.github/scripts/build_page.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: artifact.tar
          if-no-files-found: error
          name: github-pages
          retention-days: 1 # artifact will no longer be needed after page is build

      - name: Deploy GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
