name: Run Tests

on:
  push:
    branches:
      - '**'

env:
  WORKSPACE: ${{ github.workspace }}
  RUN_NUMBER: ${{ github.run_number }}

permissions: 
  contents: read
  pages: write
  id-token: write
  checks: write

jobs:
  with_spaces:
    name: Test Copy to Share
    runs-on: SASUnit_CentOS
    steps:
      - name: Copy output to share
        run: |
          touch a_file.txt
          ./.github/scripts/copy_to_p_drive.sh a_file.txt foo
